language: python

python:
    - "2.7"
    - "3.6"

before_install:
    - pip install setuptools_rust
    - pip install -r benchmarks/requirements.txt
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - export PATH="$PATH:$HOME/.cargo/bin"
    - rustup default nightly

install:
    - make install-pip-verbose

script:
    - if [[ "$TRAVIS_PYTHON_VERSION" != "2."* ]]; then make test-verbose; fi

after_success:
    - make benchmark
