language: python

matrix:
    include:
        - python: 2.7
          dist: trusty
        - python: 3.6
          dist: trusty
        - python: 3.7
          dist: xenial
          sudo: true


before_install:
    - pip install setuptools_rust
    - pip install -r benchmarks/requirements.txt
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - export PATH="$PATH:$HOME/.cargo/bin"
    - rustup default nightly

install:
    - make install-pip-verbose

script:
    - if [[ "$TRAVIS_PYTHON_VERSION" != "2."* ]]; then cargo test; fi
    - make test-verbose

after_success:
    - make benchmark
